### ISSUE TITLE
Issue's to be fixed.

### ISSUE THREAD

**Issue by facoptere** [DayZMod/DayZ#293]
- [ ] get rid of polling for bear trap events on server side. Cf. also https://github.com/R4Z0R49/DayZMod/issues/76
- [ ] Transfer his zeds/animals from a killed player to all players around
- [ ] Credit a new player kill in the journal only if the killer is close to the corpse and has opened the journal.
  boxes wiyh different count of matches...
- [ ] Remove items from inventory when the building is built, to prevent any loss during a server restart.
- [ ] Fix stacked lootpiles. Fix loot on building spawned locally on each client.cf https://github.com/R4Z0R49/DayZMod/issues/62
- [x] Cannot apply sepsis bandages to other players https://github.com/DayZMod/DayZ/issues/232
- [x] Add gates and padlock
- [ ] feign death http://forums.dayzgame.com/index.php?/topic/214707-feign-death-key/?view=getnewpost
- [ ] redo gather wood (icon only for harvestable trees) https://github.com/DayZMod/DayZ/issues/247
- [ ] fix randomly blocked throw item key https://github.com/DayZMod/DayZ/issues/252
- [x] apply bandage to other players https://github.com/DayZMod/DayZ/issues/232
- [ ] craft a good meal https://github.com/DayZMod/DayZ/issues/226
- [ ] looting a corpse shall give infection randomly https://github.com/DayZMod/DayZ/issues/222
- [ ] craft fireplace with any kind of wood (but maybe add music paper + stones to start the fire), leave rough stones when dismantled https://github.com/DayZMod/DayZ/issues/220
- [ ] add woman models
- [ ] get rid of legacy binarized models in dayz_equip
- [x] add sway in weapon according to exhaustion. https://github.com/DayZMod/DayZ/issues/237 - Priority Change.
- [ ] fix bike wheel with a tube or patch + glue + pump + a water bawl or pond http://forums.dayzgame.com/index.php?/topic/212326-suggestion-for-fixing-bicycle-wheel/
- [ ] combat logging: the character corpse stays on the map, can be killed without the presence of the actual player http://forums.dayzgame.com/index.php?/topic/211414-a-better-combat-logging-solution/
- [ ] shutdown the server after HH:MM of elapsed time. Disconnect properly all players, suspend combat logging,save everything to hive, kill the process using hivextdll entry, warn the players with a countdown in the GUI
- [x] Watchtower bells ring throughout whole Chernarus! = https://github.com/DayZMod/DayZ/issues/258
- [x] Oil Barrels Graphic Glitch 1.8.3 - https://github.com/DayZMod/DayZ/issues/257
- [x] Loot Tables add tranquilizer darts for the crossbow. (Tranquiliser_Bolt) - https://github.com/DayZMod/DayZ/issues/259
- [x] Loot Tables add explosive darts for the crossbow. (Crossbow_EX_Bolt) - https://github.com/DayZMod/DayZ/issues/259
- [x] No anim played when collecting leaves - https://github.com/DayZMod/DayZ/issues/267
- [ ] Flash Light Go's off after looting 1.8.3 - https://github.com/DayZMod/DayZ/issues/269
- [x] BloodBag Transfuse issue - https://github.com/DayZMod/DayZ/issues/279
- [x] Alice Backpack  - https://github.com/DayZMod/DayZ/issues/294
- [x] Alice Backpack - updated  [1 X weapon, 18X magazines] Should fill the gap between the Assault pack
- [ ] Achievements - https://github.com/DayZMod/DayZ/issues/295
- [x] Bloodbag issue - https://github.com/DayZMod/DayZ/issues/279 - Fix added waiting on test info
- [x] Random Survivor Skins - https://github.com/DayZMod/DayZ/issues/292 - Fix added waiting on test info

Other Issues
- [x] Players getting run over by cars don't take damage. (FreeFall issue)
- [x] Some players get stuck in a unconscious state, sitting for example and cant get out of it. This can happen after blood transfusion or knock out. I think it involves someone trying to move them as well hence the sitting. We use your DayZ Admin tool to try to heal or/and teleport them out of it. Epi Pen doesn't help either.
- [ ] Switching weapons without side arms, lying down in a building (ATC for example), will make the character stand up.
- [ ] Logging out in water kills your gear. (oldie but goldie)
- [ ] Players falling out of choppers IF they switch from backseat to gunner or vice versa, This "bug" seems intermittent, not always occurring Switching between gunner seats works. (Guessing ANTITP)
- [ ] Loot spawning inconsistently, sometimes another player needs to enter the area for loot to spawn even though 10 mins have passed. 
- [ ] Available slots not always showing in tents and stashes. This seems to be related to how you sit/stand when checking the object.
- [ ] Hero skin is gone after a hero dies and respawns. He is stuck with survivor skin unless we fix it in the database.
- [ ] Choppers not giving the option to repair them even though they are broken. This can sometimes be fixed by itself after a restart. 
- [ ] Sometimes dead players (their corpse) dissapear after being killed and the killer thinks the dead player combat logged.
- [ ] Loot in boat houses either spawn under water or in the air above the planks so to speak, if high tide you cant get to the loot under water.

**Comment by R4Z0R49** [comment]
Added to list Alice Backpack.

**Comment by Lukethero** [comment]
So much yes for feign death and gates and padlocks. For gates and padlocks I posted my ideas here https://github.com/DayZMod/DayZ/issues/284, but honestly I would be happy with anything really. Keep up the good work devs.

**Comment by ghost** [comment]
Oh, automatic restarts via the hive.dll... Now THAT's nifty!
Also, see me being flattered for adding three of my suggestions to the plan! Thanks!

**Comment by R4Z0R49** [comment]
Bloodbag issue
Random Survivor Skins

added

**Comment by R4Z0R49** [comment]
Cancel Item Stash/Sand wall bug 1.8.3 - https://github.com/DayZMod/DayZ/issues/270

Unable to recreate removed pending more info.

**Comment by R4Z0R49** [comment]
Fixed issues are pending feedback.

**Comment by Lukethero** [comment]
A huge bug that I do not see mentioned here is the big where you spawn in with survivor skin, regardless of your humanity. This problem is fixed once the players humanity is updated, and the proper skin is put on. This does not seem like a big issue but it is very frustrating for friendly players who think they have spotted a survivor just to find out that it is a bandit who has not changed skins yet. I have also heard about survivors getting bandit skins and having it change back the same way, but I think that is bullshit.

**Comment by HeroSmurf** [comment]
Right; good one. 

Can you post that login problem as it's own issue Luke? 
Oh and while you're at it truncate the last 6 words; should help whoever is working on it :)

**Comment by TeaObvious** [comment]
Restart using hiveext is a good idea, to do this i used this kind of code since a long time:
void __stdcall _RVExtension(char *output, int outputSize, const char *function) { 
  if (strcmp(function, "terminate") == 0) {
    ExitProcess(0);
  } else {
    strncpy(output, function, outputSize); 
  }
}

It is a bad behavior of an dll to call ExitProcess, but in this case this what we want, even thou it has some side effects:
https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658%28v=vs.85%29.aspx

If you use this way the hive should disconnect all connections to the Database and block new requests.
To disconnect the users i used endMission but i did not save everything.

**Comment by R4Z0R49** [comment]
Yea, we wont be adding one to the dlls. But thanks
