### ISSUE TITLE
1.8.8, Problems

### ISSUE THREAD

**Issue by R4Z0R49** [DayZMod/DayZ#755]
- [ ] Weapon Switch still reported not working correctly 
- [ ] Wall and gate play balance. #771
- [ ] open Target reported not working.
- [ ] Fireplaces despawning, not staying lit when more fuel is added.
- [ ] humanity not working/syncing correctly. 
- [ ] Add animation to switch skin, https://github.com/DayZMod/DayZ/issues/754
- [x] flys spawning on logout/login.
- [x] Floating loot.
- [x] ItemAntibiotic still reported not reducing when given to another player.
- [x] Fixed Tranq Bolt.
- [x] Key handler not registering new keys. (turbo[]={};, load game then setup key)
- [x] Confirmed kills registers murders for all kills.
- [x] Blowing up a vehicle with players inside does not effect the players. 
- [x] player names now showing in server log after death.9:20:20 "Player UID#**\* CID#**\* PID#14(unknown) as Survivor2_DZ died at Электрозаводск [104:131]"
- [x] players who apply a splint to another player do not get +humanity (brokeBones.sqf)
- [x] Find a way to block the turbo key.
- [x] Study Body issue with confirmed kills. Allows limitless amounts to be displayed in Journal.
- [x] Action key issue with hold breath allowing perfect aim.

**Comment by skigoggles** [comment]
players who apply a splint to another player do not get +humanity (brokeBones.sqf)

**Comment by romanongit** [comment]
Flying loot.
![20161010221914_1](https://cloud.githubusercontent.com/assets/6949874/19259485/4ebfb9f2-8f82-11e6-9285-7dbf9213f076.jpg)

**Comment by skigoggles** [comment]
i know i've seen the flying loot near the harbor cranes before, but not the buildings

**Comment by romanongit** [comment]
I've seen it also floating above other buildings in 1.8.8, like fire stations for instance. Looks like a broken vertical displacement transformation.

**Comment by Inurosen** [comment]
Switching primary and melee weapon with hotkeys sometimes doesn't switch them. It's taking your weapon away and getting it back instead of another one. Usually happens after opening your gear (not always).

**Comment by romanongit** [comment]
Confirmed bandit kills show up as murders in journal. Tested three times this afternoon on Europa.

**Comment by R4Z0R49** [comment]
Its already on the list and has had a fix applied just needs testing

**Comment by SecretsUSA** [comment]
Tent spam still broken.

**Comment by romanongit** [comment]
Can confirm that spamming "rest" at tents still works sometimes.
Any update on the floating loot? That's a really annoying one.

**Comment by AndrewEscocia** [comment]
I have tried spamming rest and it seems to be fine for me, afaik I have only used camping tents so far , no other specific circumstances spring to mind

**Comment by romanongit** [comment]
I would suspect https://github.com/DayZMod/DayZ/commit/7e413848fb0953a81f1822b444e065cfc0675d21#diff-299d861e008c46221bf1ef211f97be46 to be the cause for the floating loot. It would explain why it's floating only near the coast.

**Comment by romanongit** [comment]
Here's another one: One of the field hospitals in Cherno is ill-positioned in 1.8.8. I checked the positioning data of the USMC_WarfareBFieldhHospitals, they haven't changed. So my guess is that it's related to the floating loot.

![224580_20161030152514_1](https://cloud.githubusercontent.com/assets/6949874/19977144/d9f7de3c-a1f2-11e6-9972-0e51b87d6e0f.jpg)

**Comment by romanongit** [comment]
Guys, is anyone reading this? What else can I do to help fixing this?

**Comment by ebaydayz** [comment]
That's how that tent has always been positioned @romanongit You can enter from the other entrance.

I'll move it back a little so you can enter from both doors.

**Comment by romanongit** [comment]
I'm absolutely sure that the entrance wasn't blocked prior to 1.8.8 @ebaydayz . Here's a snapshot from Sept 19, 2016, version 1.8.7.

![tent_cherno_1 8 7](https://cloud.githubusercontent.com/assets/6949874/20449618/d0fe7b98-adea-11e6-83df-b41fa53766f5.jpg)

Anyway, I was referring to the floating loot when I asked if there was a way I could help.

**Comment by ebaydayz** [comment]
Ok, the actual coordinates haven't changed at all since the original, but the lootable town generator objects were recently moved to global instead of local in aedc787, so that could account for the slight position offset. I fixed that one with 7e18cef.

The floating loot is most likely due to 7e41384 as you mentioned above. That commit will most likely be reverted. It was meant to fix the loot position in boat houses, but ended up causing issues with land buildings (including ones that are not in the town generator like schools, cranes, etc.).

**Comment by M0tzilla** [comment]
if 7e41384
<https://github.com/DayZMod/DayZ/commit/7e413848fb0953a81f1822b444e065cfc0675d21>
is reverted does that mean that we're going to lose the fishing poles
again?

**Comment by ebaydayz** [comment]
No, we can probably just change it to:
```sqf
if (boatHouse) then {
    //use setPos
} else {
    //use setPosATL
};

Since the boathouse is the only lootable building over water.

**Comment by skigoggles** [comment]
@ebaydayz I know I've been seeing floating loot above other buildings - certainly the factory building with the metal plates as ramps in solichny - its has to be related (the crames have been like that forever). If we move forward or backward we're going to have loot location issues, so whichever way we're going, if we can get a list,  I can quickly get new coords.

**Comment by R4Z0R49** [comment]
Yea rgr i've added it to the list just waiting to get some time to try and debug whats going on with it.
